### ISSUE TITLE
Mesh or B-rep version of the dataset?

### ISSUE THREAD

**Issue by GericoVi** [HARRIXJANG/ASIN-master#1]
Thanks for this work. I was wondering if it is possible for you to provide mesh (labelled STLs?) or b-rep (labelled STEP files?) versions of the publicly available dataset?

For testing other 3D deep learning methods against this machining features dataset.

**Comment by HARRIXJANG** [comment]
I am so sorry. I do not have the permission to provide the labelled STLs data.

**Comment by kwonminho8314** [comment]
Thanks for this work :) 
if you could tell me how to use Predict_data_prep.py to predict my data, I would greatly appreciate it.

I encountered an error message that the pointdatasPoF could not be converted to an np array due to different shapes in the list, and I was curious as to why this error occurred.
